export const ACT1_INTRO_LINES = [
  "The road to Saltmere Point shimmered beneath the afternoon heat.",
  "Golden fields stretched endlessly on either side of the cracked asphalt, disturbed only by the occasional crooked windmill or skeletal tree leaning toward the distant sea. Somewhere far off, gulls circled lazily above white cliffs glowing beneath the summer sun.",
  "It should have felt peaceful, instead, it felt abandoned.",
  "Rik had assured everyone this trip would be easy enough. A few errands before the wedding. Checking up on the wedding invitations, hiring a band for the wedding, retrieve a package from storage and some other small errands. Nothing unusual, nothing worth worrying about. Yet as their train pulled into the quiet station of Saltmere Point, an uncomfortable silence settled over the group. Beyond the station, the streets were almost empty, with only a few people passing by. The locals they did see kept staring before forcing a smile, and several clocks in shop windows showed completely different times. Still, Rik had not come alone.",
  "Jur carried himself with a restless, almost infectious energy, always seeming on the edge of distraction or discovery. His sharp wit and quicker hands made him useful in difficult situations—though it also meant he couldn’t always be trusted around anything left unattended.",
  "Romin followed close behind, carefully studying maps, symbols, and old notices pinned throughout the town square. He had a habit of stopping at every map, notice, or symbol they passed, insisting on taking a closer look. Though every uneven staircase and loose cobblestone threatened catastrophic consequences for his notoriously fragile bones.",
  "Maikel had an easy, almost childlike enthusiasm, finding enjoyment in nearly everything around him—from the weather to the smallest architectural details. His curiosity often pulled him toward things best left alone, though it was matched by a tendency to immediately worry about the consequences afterward.",
  "Ingmar trudged behind the others like an unwilling bodyguard assigned to babysit fools. Broad-shouldered, blunt, and permanently unimpressed, he watched every local with suspicion and seemed only moments away from throwing someone directly into the sea.",
  "And then there was Robin. Dressed as though he expected photographers at any moment, he carried himself with effortless confidence. He had a remarkable eye for beauty and value, naturally drawn to rare objects and overlooked details—though that same instinct was paired with an almost naive willingness to trust whoever stood in front of him.",
  "Together they entered the heart of Saltmere Point beneath a blazing white sun but none of them noticed the old fishermen quietly leaving the harbor as they arrived. None of them heard the church bell ring thirteen times at noon. And none of them saw the tall figure standing motionless atop the distant cliffs, watching the Groom’s return.",
  "Beneath the village, buried deep below its streets and stone, something ancient shifted in its sleep."
];
